name: anlifecycle
description: AnLifecycle draws on lifecycle in androidx to implement lifecycle on Flutter, Developers can sense the LifecycleState under the current context wherever you need it.
version: 3.6.0
homepage: https://github.com/aymtools/lifecycle/
issue_tracker: https://github.com/aymtools/lifecycle/issues
topics:
  - lifecycle
  - androidx
  - androidx-lifecycle
  - life
  - resume

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1

  flutter_lints: any

flutter:

